repos:
- hooks:
  - id: trailing-whitespace
  - id: check-added-large-files
  - id: check-ast
  - id: check-docstring-first
  - id: debug-statements
    language_version: python3
  - id: check-executables-have-shebangs
  - id: check-json
  - id: check-yaml
  - id: detect-private-key
  - id: end-of-file-fixer
  - id: fix-encoding-pragma
  - args:
    - --branch
    - staging
    - --branch
    - development
    - --branch
    - staging
    - --branch
    - production
    id: no-commit-to-branch
#  - id: pretty-format-json
  - id: requirements-txt-fixer
  repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.2.0
- hooks:
  - id: flake8
    language_version: python3
  repo: https://github.com/PyCQA/flake8
  rev: 4.0.1
# - hooks:
#   - id: bandit
#   repo: https://github.com/PyCQA/bandit
#   rev: 1.7.4
- hooks:
  - id: pydocstyle
  repo: https://github.com/PyCQA/pydocstyle
  rev: 6.1.1
- hooks:
  - id: pylint
  repo: https://github.com/PyCQA/pylint
  rev: v2.13.7
- hooks:
  - id: isort
  repo: https://github.com/PyCQA/isort
  rev: 5.10.1
- hooks:
  - id: commitizen
    stages:
    - commit-msg
  repo: https://github.com/commitizen-tools/commitizen
  rev: v2.24.0
